/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SainsburysTechTest;

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;

public class SainsburysTechTest {
	
	private GroceryService service;
	
	@Before
	public void setUp() throws MalformedURLException{
		service = new GroceryService("https://jsainsburyplc.github.io/serverside-test/site/www.sainsburys.co.uk/webapp/wcs/stores/servlet/gb/groceries/berries-cherries-currants6039.html");	
	}
	
    @Test
    public void testGetGroceryProductsAsHTML() throws IOException {
    	
    	
    	String response = service.getGrocerciesAsHTML();
    	System.out.println(response);
        assertNotEquals(response, "");
    }
   
    @Test
    public void testGetGrocerySummaryAsJSON() throws IOException {
    	String response = service.getGroceriesSummaryAsJSON();
    	
    	assertNotEquals(response, "");   	
    }
}
